<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '8f355d6743dc63d22561074544485410',
  'DATABASE_URL' => 'mysql://z021tuu70zonifts:yp4unara7ith86kl@vlvlnl1grfzh34vj.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/v79drceean85s0pz',
  'MAILER_DSN' => 'smtp://mail.gandi.net:465?encryption=ssl&auth_mod=login&username=accueil@enlienavecvous.org&password=Gestalthost2020',
  'PROJECT_URL' => 'https://onestlapourvous.herokuapp.com',
  'PROJECT_ADDR' => 'onestlapourvous.herokuapp.com',
  'API_URL' => '\'https://onestlapourvous.herokuapp.com/api/\'',
  'CORS_ALLOW_ORIGIN' => '^http?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'CORS_ALLOW_ORIGIN_IPIFY_API' => '^https://api.ipify.org/?format=json$',
  'MAILER_URL' => 'smtp://mail.gandi.net:465?encryption=ssl&auth_mod=login&username=accueil@enlienavecvous.org&password=Gestalthost2020',
  'API_LOGIN' => 'onestlapourvous',
  'API_KEY' => 'so4c0d00de65b6aae5842f3e6f4a32040c0f5f7058',
);
