<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '8f355d6743dc63d22561074544485410',
  'DATABASE_URL' => 'mysql://z021tuu70zonifts:yp4unara7ith86kl@vlvlnl1grfzh34vj.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/v79drceean85s0pz',
  'MAILER_DSN' => 'smtp://accueil@enlienavecvous.org:Clempro2020@mail.gandi.net:587',
  'PROJECT_URL' => 'https://127.0.0.1:8000',
  'PROJECT_ADDR' => '127.0.0.1:8000',
  'API_URL' => '\'https://127.0.0.1:8000/api/\'',
  'CORS_ALLOW_ORIGIN' => '^http?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'MAILER_URL' => 'null://localhost',
  'API_LOGIN' => 'onestlapourvous',
  'API_KEY' => 'so4c0d00de65b6aae5842f3e6f4a32040c0f5f7058',
  'TRUSTED_HOSTS' => '^(localhost|onestlapourvous.herokuapp\\.com)$',
);
